### ISSUE TITLE
Question about relative imports

### ISSUE THREAD

**Issue by dzid26** [JesusFreke/fusionIdea#12]
I was trying to debug following [plugin](https://github.com/tapnair/OctoFusion). 
It works when simply imported inside Fusion360. But when running from PyCharm, it errors out with 
> attempted relative import without known parent.

On lines in octoFusionCommand.py or OctoFusion_Old.py containing the following imports:
`from .packages import requests`,
`from ....packages import requests`,
`from .Fusion360CommandBase import Fusion360CommandBase` etc
In the end, I was able to import those modules by **removing** dots in front of the modules names. 

Do you think the issue is related to Python version or FusionIdea plugin? I am trying to figure out how all of this works.

**Comment by JesusFreke** [comment]
Ideally, running from IDEA should behave similarly to running from Fusion directly. Do you have a simple example of a script/directory setup that reproduces this issue?

**Comment by dzid26** [comment]
Oh, I didn't notice your reply,
I basically cloned https://github.com/tapnair/OctoFusion plugin. In PyCharm, I set the interpreter as _Fusion 360 Python SDK_ and checked "Fusion 360 Support Enabled" checkbox.
Then right-click on OctoFusion.py -> Debug in Fusion 360 and it complains about the relative imports.

**Comment by JesusFreke** [comment]
Great, thanks. That should be enough to let me take a look at it

**Comment by JesusFreke** [comment]
After a ton of digging, I finally made some progress on this at least. I was able to figure out how to get relative imports working, but now I'm running into another issue when trying to run the OctoFusion plugin from IDEA

    Traceback (most recent call last):
      File "Z:\projects\OctoFusion\Fusion360CommandBase.py", line 170, in onRun
        commandDefinition_ = commandDefinitions_.addButtonDefinition(self.cmdId, self.commandName, self.commandDescription, self.commandResources)
      File "C:/Users/jesusfreke/AppData/Local/Autodesk/webdeploy/production/8b802e7a3c3d3db523b64fd80db49d9f63efcaf3/Api/Python/packages\adsk\core.py", line 4268, in addButtonDefinition
        return _core.CommandDefinitions_addButtonDefinition(self, *args)
    RuntimeError: 3 : the relative resourceFolder path not found

**Comment by JesusFreke** [comment]
Actually, I have a suspicion what the problem might be there. I suspect since the script is essentially running in the context of the fusion_idea_addin addin, it's probably looking for the resources relative to the fusion_idea_addin's directory.

If that's the case.. I can't really think of a good way to get that working. Although there may be some bad ways to get it working. e.g. wrapping+replacing the various functions that accept a resource.. or maybe actually copying in the contents of the add-in being run into fusion_idea_addin's directory.  But both of those are... a bit ewww :)

**Comment by JesusFreke** [comment]
I've updated the fusion_idea_addin with the fix for the relative imports.

I don't see any good way to transparently handle the relative resource paths though. I think the best option may be to modify the add-in and convert any relative resource path to an absolute one. e.g.

```python
def resolve_relative_resource(path):
    script_dir = os.path.dirname(__file__)
    return os.path.normpath(os.path.join(script_dir, path)) 
```
