### ISSUE TITLE
"Unhandled exception while importing and running script"

### ISSUE THREAD

**Issue by NyxCode** [JesusFreke/fusionIdea#16]
Fusion throws this error at me when running / debugging:
```
Unhandled exception while importing and running script.
Traceback (most recent call last):
  File "C:/Users/morit/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/fusion_idea_addin/fusion_idea_addin.py", line 331, in notify
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 580, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

**Comment by JesusFreke** [comment]
hmm. It looks like importlib.util.spec_from_file_location is returning None when creating an import spec for the script that's being run. 

I was able to reproduce this if I created a script with a non-standard extension (e.g. no extension) and overrode the file type in IDEA, and tried to run that. Does the script you're trying to run have a non-standard file extension or anything?

I just pushed https://github.com/JesusFreke/fusion_idea_addin/commit/a4d43cbcf4b9f2c177f99bf055e77329a3650ac9 which fixes the problem for that specific case at least.

**Comment by NyxCode** [comment]
Hey, thanks for the quick response!
I now updated the fusion addin as well as PyCharm and the fusionIdea plugin.
When I either do "Run in Fusion 360" or "Debug in Fusion 360", my addin is started within fusion after I enter the key hash. However, I do not see any console output, and the debugger is not attached.
When I do "Run in Fusion 360", i just see
```
Public key hash: 65E9F2D25E79AA8B9EC13D12BB27D4191547202D
Server stopped.
```
When I debug, I just see
```
Public key hash: 65E9F2D25E79AA8B9EC13D12BB27D4191547202D
Attaching to Fusion 360 process with PID=7036
Connected to pydev debugger (build 213.7172.26)
Server stopped.
```

**Comment by NyxCode** [comment]
Maybe I am missing something here - Are Fusion addons even supported?

**Comment by JesusFreke** [comment]
When running/debugging from IDEA/PyCharm, it will import the script into Fusion's python environment, run the "run" method, and then disconnect once the run method returns.

I'm not actually sure what happens if you try to register for events or add buttons or stuff, like an add-in normally would.  Since the add-in code is actually running in the context of the fusion_idea_addin as far as Fusion is concerned, I would guess it should probably work, but the events and such would just be associated with the fusion_idea_addin addin.

Another approach would be to install your add-in as an actual add-in in fusion, and then set a breakpoint in an event handler or whatever in IDEA/PyCharm, and attach to the fusion process (Run->Attach to process in IDEA). Then, when the event is triggered, it should hit the breakpoint in IDEA/PyCharm and you can continue debugging from there.

**Comment by NyxCode** [comment]
@JesusFreke I see, makes sense!  
> Another approach would be to install your add-in as an actual add-in in fusion, and then set a breakpoint in an event handler or whatever in IDEA/PyCharm, and attach to the fusion process (Run->Attach to process in IDEA). Then, when the event is triggered, it should hit the breakpoint in IDEA/PyCharm and you can continue debugging from there.  

I somehow can't get PyCharm to connect to the Fusion process like VSCode does, no matter what I do.

**Comment by NyxCode** [comment]
I don't know much/anything about how python debugging works, but I suspect the "Debug" button within Fusion starts a debugging server to which VSCode then connects. No idea how to set this up in pycharm though. Through the "Attach to Process.." dialog in PyCharm, I cannot connect to any process

**Comment by JesusFreke** [comment]
Hmm. Attach to process works for me in pycharm.

First, make sure fusion 360 support is enabled for the project (Settings -> Languaged & Frameworks -> Fusion 360 -> Fusion 360 Support Enabled).

Then Run->Attach to Process, and you should see the fusion process in the "Fusion 360 Processes" section

![image](https://user-images.githubusercontent.com/106383/159990311-c971637a-00df-4cb6-be45-565fefa23051.png)

And then, when it attaches, this is the console output:

```
Public key hash: xxxxxxxx
Attaching to a process with PID=23044 and port=61572
Connected to pydev debugger (build 213.6777.50)
```

**Comment by NyxCode** [comment]
@JesusFreke 
After I enter the hash in the Fusion popup, Fusion freezes and nothing happens in the debugger. The freeze is only resolved by restarting Fusion, stopping the debugger does not help.
Are there logs somewhere I could share with you?
